#!/bin/sh
### BEGIN INIT INFO
# Provides:          reth
# Required-Start:    reth-sync
# Required-Stop:     
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Reth Node
# Description:       Start and stop the reth daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/reth
NAME=reth
DESC="Reth Node"
PIDFILE=/var/run/reth.pid
LOGFILE=/var/log/reth.log
RETH_USER=reth
ETH_GROUP=eth
RETH_DIR=/persistent/reth
JWT_SECRET_FILE=/tmp/jwt.hex

start() {
	echo -n "Starting $DESC: "
	echo "Starting $DESC" > /tmp/system-api.fifo

	# Ensure the reth log file exists and has correct permissions
  	touch $LOGFILE
  	chown $RETH_USER:$ETH_GROUP $LOGFILE

	# Ensure the RETH_DIR exists and has correct permissions
	mkdir -p $RETH_DIR
	chown -R $RETH_USER:$ETH_GROUP $RETH_DIR

	# Check if the JWT_SECRET_FILE exists and exit with a message if it doesn't
	if [ ! -f $JWT_SECRET_FILE ]; then
		echo "JWT secret file not found at $JWT_SECRET_FILE. Exiting."
		exit 1
	fi

	start-stop-daemon -S --make-pidfile -p $PIDFILE -c $RETH_USER:$ETH_GROUP -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
		node \
		--full \
		--datadir "$RETH_DIR" \
		--authrpc.addr 127.0.0.1 \
		--authrpc.jwtsecret "$JWT_SECRET_FILE" \
		--authrpc.port 8551 \
		--http \
		--http.addr 127.0.0.1 \
		--http.port 8545 \
		--http.api "eth,net,web3,trace,rpc,debug,txpool" \
		--ws \
		--ws.addr 127.0.0.1 \
		--ws.port 8546 \
		--ws.api "eth,net,trace,web3,rpc,debug,txpool" \
		--log.stdout.format json \
		--log.file.max-files 0 \
		--metrics "127.0.0.1:9001" \
		2>&1 | tee ${LOGFILE}"
	echo "$NAME."
}

stop() {
    echo "Stopping $NAME"
    echo "Stopping $NAME" > /tmp/system-api.fifo
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        # Find all child processes of the shell process
        PIDS="$PID $(pgrep -P $PID)"

        # Send SIGTERM to all processes
        for pid in $PIDS; do
            kill -TERM $pid 2>/dev/null
        done

        # Send SIGKILL to any remaining processes
        for pid in $PIDS; do
            kill -KILL $pid 2>/dev/null
        done

        rm -f $PIDFILE
    else
        echo "$PIDFILE not found, $NAME may not be running"
    fi
    echo "$NAME stopped"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0
