#!/bin/sh
exec 2>&1

# Set up directories
mkdir -p /persistent/reth
chown reth:eth /persistent/reth

# Get latest version and sync
LATEST_META=$(rclone --config /etc/rclone.conf cat r2:chain-db-snapshots/reth-mainnet-full/latest_version.meta.txt)
echo "Latest meta: $LATEST_META"

rclone sync --config /etc/rclone.conf -v -P \
    --transfers=20 --multi-thread-streams 30 \
    --contimeout=10m --retries 10 --retries-sleep 60s \
    --error-on-no-transfer --update --fast-list \
    --delete-during --disable-http2 --no-gzip-encoding \
    --exclude 'files.txt' \
    r2:chain-db-snapshots/reth-mainnet-full/$LATEST_META/ /persistent/reth

touch /tmp/reth-sync.done
exec pause