#!/bin/sh
### BEGIN INIT INFO
# Provides:          networking
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set up networking
### END INIT INFO

case "$1" in
  start)
    ip link set lo up
    ip addr add 127.0.0.1/8 dev lo
    ip link set eth0 up
    echo nameserver 8.8.8.8 > /etc/resolv.conf
    echo nameserver 8.8.4.4 >> /etc/resolv.conf
    chattr +i /etc/resolv.conf # don't use dhcp dns
    exec udhcpc -i eth0 -f &
    ;;
  stop)
    killall udhcpc
    ip link set eth0 down
    ip addr del 127.0.0.1/8 dev lo
    ip link set lo down
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
