#!/bin/sh

# Mount essential filesystems
mkdir -p /dev /proc /sys /run
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /run
mount -t configfs none /sys/kernel/config

# Execute systemd
exec /lib/systemd/systemd systemd.unit=minimal.target
