#!/bin/sh

# Mount essential filesystems
mkdir -p /dev /proc /sys /run
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /run
mount -t configfs none /sys/kernel/config

# Workaround to make pivot_root work
# https://aconz2.github.io/2024/07/29/container-from-initramfs.html
exec unshare --mount sh -c '
    mkdir /@
    mount --rbind / /@
    cd /@ && mount --move . /
    exec chroot . /lib/systemd/systemd systemd.unit=minimal.target'
